# Generated by Django 4.0.4 on 2022-06-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacoes',
            fields=[
                ('estacao', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horario', models.CharField(blank=True, max_length=19, null=True)),
                ('livre', models.IntegerField(blank=True, null=True)),
                ('id_reserva', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estacoes',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('meu_time', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, max_length=10, null=True)),
                ('reserva_inicia_em', models.CharField(blank=True, max_length=8, null=True)),
                ('reserva_termina_em', models.CharField(blank=True, max_length=8, null=True)),
                ('check_in_em', models.CharField(blank=True, max_length=19, null=True)),
                ('check_out_em', models.CharField(blank=True, max_length=19, null=True)),
                ('id_estacao', models.ForeignKey(blank=True, db_column='id_estacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.estacoes')),
                ('id_funcionario', models.ForeignKey(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.funcionarios')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
